version: '3.4'

services:
  alasimvar.api:
    image: alasimvar:dev
    container_name: AlasimVar.API
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "AlasimVar.API"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - /Users/fatihmandirali/Documents/ws/lessons/docker-project/AlasimVar.API/AlasimVar.API:/app
      - /Users/fatihmandirali/Documents/ws/lessons/docker-project/AlasimVar.API:/src
      - /Users/fatihmandirali/vsdbg/vs2017u5:/remote_debugger:rw
      - /Users/fatihmandirali/.nuget/packages/:/root/.nuget/packages:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net7.0/AlasimVar.API.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true